sudo: true
dist: trusty
language: java

addons:
  apt:
    sources:
      - deadsnakes
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - python3.5-dev

before_install:
  - sudo sh -c 'echo "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-5.0 main" > /etc/apt/sources.list.d/llvm.list'
  - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -
  - sudo apt-get update -q || true
  - sudo apt-get install clang-format-5.0 -y
  - sudo sh -c "'\n' | add-apt-repository ppa:ubuntu-toolchain-r/test" 
  - sudo apt-get update
  - sudo apt-get upgrade
  - sudo apt-get dist-upgrade

install:
  - strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
  - wget https://bootstrap.pypa.io/get-pip.py
  - sudo python3.5 get-pip.py
  - python3.5 -m pip install --user wpiformat
  - mkdir -p $HOME/latest-gcc-symlinks  # see travis-ci/travis-ci#3668
  - ln -s /usr/bin/g++-6 $HOME/latest-gcc-symlinks/g++
  - ln -s /usr/bin/gcc-6 $HOME/latest-gcc-symlinks/gcc
  - export PATH=$HOME/latest-gcc-symlinks:$PATH

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
  - strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
  - gcc --version
  - g++ --version
  - ./gradlew build
