version: 1.0.{build}
image: Visual Studio 2015

platform:
- x86
- x64

clone_script:
- cmd: >-
    git clone -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%

    cd %APPVEYOR_BUILD_FOLDER%

    git checkout -qf %APPVEYOR_REPO_COMMIT%

    git submodule update --init --recursive

build_script:
- ps: >-
    mkdir build

    $ProgressPreference = 'SilentlyContinue'

    if ($env:PLATFORM -eq "x86") {
      echo "32 Bit"

      wget "https://github.com/wpilibsuite/frc-openjdk-windows/releases/download/v11.0.0u28-1/jdk-x86-11.0.0u28-1.zip" -O "build\jdk.zip"

      $Env:JAVA_HOME = "$pwd/build/jdkinst/jdk"
    }
    else {
      echo "64 bit"

      wget "https://download.java.net/java/ga/jdk11/openjdk-11_windows-x64_bin.zip" -O "build\jdk.zip"

      $Env:JAVA_HOME = "$pwd/build/jdkinst/jdk-11"
    }
    Expand-Archive build\jdk.zip -DestinationPath build/jdkinst

    dir

    dir build

    dir build\jdkinst

- cmd: gradlew.bat build jacocoTestReport publishToMavenLocal -PciBuild
- cmd: mkdir "build\publish_artifacts"
- cmd: xcopy /s "%USERPROFILE%\.m2\repository\com\snobot\simulator" "build\publish_artifacts"

after_build:
- cmd: "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
- cmd: pip install codecov
- cmd: codecov -f "snobot_sim_gui/build/reports/jacoco/test/jacocoTestReport.xml"
- cmd: codecov -f "snobot_sim_java/build/reports/jacoco/test/jacocoTestReport.xml"
- cmd: codecov -f "snobot_sim_jni/build/reports/jacoco/test/jacocoTestReport.xml"

test_script:
- ps: >-
    # upload results to AppVeyor

    $wc = New-Object 'System.Net.WebClient'

    $files = Get-ChildItem ./snobot_sim_java/build/test-results/test/

    for ($i=0; $i -lt $files.Count; $i++) {

       $the_file = $files[$i].Name

       $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path snobot_sim_java/build/test-results/test/$the_file))

    }

    $files = Get-ChildItem ./snobot_sim_jni/build/test-results/test/

    for ($i=0; $i -lt $files.Count; $i++) {

       $the_file = $files[$i].Name

       $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path snobot_sim_jni/build/test-results/test/$the_file))

    }

    $files = Get-ChildItem ./snobot_sim_gui/build/test-results/test/

    for ($i=0; $i -lt $files.Count; $i++) {

       $the_file = $files[$i].Name

       $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path snobot_sim_gui/build/test-results/test/$the_file))

    }




artifacts:

- path: snobot_sim_gui/build/test-results
  name: testResults

- path: build/publish_artifacts
  name: full_maven_repo
