version: 1.0.{build}
image: Visual Studio 2015

build_script:
- cmd: gradlew.bat :temp_hal_sim:build build jacocoTestReport publish -Pmaven_repo=build/maven_repo -x checkstyleTest -x findbugsTest -x pmdTest

after_build:
- cmd: "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
- cmd: pip install codecov
- cmd: codecov -f "snobot_sim_gui/build/reports/jacoco/test/jacocoTestReport.xml"
- cmd: codecov -f "snobot_sim_java/build/reports/jacoco/test/jacocoTestReport.xml"
- cmd: codecov -f "snobot_sim_jni/build/reports/jacoco/test/jacocoTestReport.xml"

test_script:
- ps: >-
    # upload results to AppVeyor

    $wc = New-Object 'System.Net.WebClient'

    $files = Get-ChildItem ./snobot_sim_java/build/test-results/test/

    for ($i=0; $i -lt $files.Count; $i++) {

       $the_file = $files[$i].Name

       $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path snobot_sim_java/build/test-results/test/$the_file))

    }

    $files = Get-ChildItem ./snobot_sim_jni/build/test-results/test/

    for ($i=0; $i -lt $files.Count; $i++) {

       $the_file = $files[$i].Name

       $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path snobot_sim_jni/build/test-results/test/$the_file))

    }

    $files = Get-ChildItem ./snobot_sim_gui/build/test-results/test/

    for ($i=0; $i -lt $files.Count; $i++) {

       $the_file = $files[$i].Name

       $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path snobot_sim_gui/build/test-results/test/$the_file))

    }




artifacts:

- path: snobot_sim_gui/build/test-results
  name: testResults

- path: build/maven_repo/com/snobot/simulator/snobot_sim_jni/**/snobot_sim_jni-*.jar
  name: simulator_jni

- path: build/maven_repo/com/snobot/simulator/snobot_sim_java/**/snobot_sim_java-*.jar
  name: simulator_java

- path: build/maven_repo/com/snobot/simulator/snobot_sim_gui_application/**/snobot_sim_gui_application*.zip
  name: simulator_application

- path: build/maven_repo/com/snobot/simulator/snobot_sim_gui/**/snobot_sim_gui*.jar
  name: simulator_gui

- path: build/maven_repo/com/snobot/simulator/snobot_sim_gui_eclipse_boilerplate/**/snobot_sim_gui_eclipse_boilerplate-*.zip
  name: eciplse_boilerplate

- path: build/maven_repo
  name: full_maven_repo
