package com.snobot.simulator.wrapper_accessors.java;

/*
 * Autogenerated file! Do not manually edit this file. This version is regenerated
 * any time the publish task is run, or when this file is deleted.
 */

public final class JaveSimulatorVersion {
    public static final String Version = "Local build.  Last commit: f906aaa";
}