/*
 * Autogenerated file! Do not manually edit this file. This version is regenerated
 * any time the publish task is run, or when this file is deleted.
 */
#include "SnobotSim/SnobotSimHalVersion.h"

const char* SnobotSim::GetSnobotSimVersion()
{
    return "Local build.  Last commit: f906aaa";
    ;
}
